quarkus:
  http:
    port: 8080
    cors:
      enabled: true
      origins: "http://localhost:4200"
      methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      headers: "Accept,Authorization,Content-Type,Origin,X-Requested-With"
      exposed-headers: "Content-Type,Authorization"
      access-control-max-age: 24H
      allow-credentials: true

  smallrye-jwt:
    enabled: true

  log:
    console:
      json: false
      enable: true
      format: "%d{HH:mm:ss} %highlight{%-5p} [%c{1}] %s%e%n"
    level: INFO
    category:
      io.smallrye.jwt:
        level: INFO
      io.quarkus.security:
        level: INFO

  rest-client:
    auth-api:
      scope: jakarta.inject.Singleton
    account-api:
      scope: jakarta.inject.Singleton

  keycloak:
    devservices:
      enabled: false

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: users-issuer

# REST CLIENT (formato que funciona)
auth-api/mp-rest/url: "http://localhost:8081"
auth-api/mp-rest/providers: "br.edu.ifrs.orch.exception.RestClientExceptionMapper"

account-api/mp-rest/url: "http://localhost:8082"
account-api/mp-rest/providers: "br.edu.ifrs.orch.exception.RestClientExceptionMapper"

pw2:
  message: "hello"
  name: "abelha"
