quarkus:
  http:
    port: 8080
    cors:
      enabled: true
      origins: "http://localhost:4200"
      methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      headers: "Accept,Authorization,Content-Type,Origin,X-Requested-With"
      exposed-headers: "Content-Type,Authorization"
      access-control-max-age: 24H

  smallrye-jwt:
    enabled: true

  log:
    console:
      json: false
      enable: true
#      format: "%d{HH:mm:ss} %highlight{%-5p} [%c{1}] %s%e%n"
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId} [%c] %s%e%n"
    level: INFO
    category:
      io.smallrye.jwt:
        level: INFO
      io.quarkus.security:
        level: INFO
    #############################
    # ðŸ“˜ Graylog (GELF)
    #############################
    handler:
      gelf:
        enabled: true
        host: localhost
        port: 12201
        include-full-mdc: true


#  http://localhost:16686/
  otel:
    service:
      name: orch-service
    exporter:
      otlp:
        traces:
          endpoint: http://localhost:4317
          protocol: grpc
    traces:
      sampler: always_on

  rest-client:
    auth-api:
      scope: jakarta.inject.Singleton
    account-api:
      scope: jakarta.inject.Singleton

  keycloak:
    devservices:
      enabled: false

  smallrye-metrics:
    enabled: true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: users-issuer

# REST CLIENT (formato que funciona)
auth-api/mp-rest/url: "http://localhost:8081"
auth-api/mp-rest/providers: "br.edu.ifrs.orch.exception.RestClientExceptionMapper"

account-api/mp-rest/url: "http://localhost:8082"
account-api/mp-rest/providers: "br.edu.ifrs.orch.exception.RestClientExceptionMapper"

pw2:
  message: "hello"
  name: "abelha"
